---

- name: Create a {{ application_name }} production server
  hosts: all
  sudo: yes
  sudo_user: root
  remote_user: ubuntu
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/production
    - group_vars/all
    - group_vars/dbservers
    - group_vars/webservers

  roles:
#    - base
#    - db
    - web