---

- name: Create {{ application_name }} virtual machine via vagrant
  hosts: all
  sudo: yes
  remote_user: vagrant
  sudo_user: root
  vars:
    - prepare_git_repo: no
  vars_files:
    - group_vars/all
    - group_vars/dbservers
    - group_vars/webservers

  roles:
    - base
    - db
    - web
